import Head from "next/head";
import Layout from "./components/Layout";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "./components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "../lib/Icons";
import HireMe from "./components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import { useState, useEffect } from "react";

export default function Home() {
  const [isEasterEggVisible, setEasterEggVisible] = useState(false);

  const handleLightBulbClick = () => {
    setEasterEggVisible(true);

    // Ocultar el Easter egg después de 10 segundos
    setTimeout(() => {
      setEasterEggVisible(false);
    }, 5000);
  };

  useEffect(() => {
    if (isEasterEggVisible) {
      const handleClickOutside = () => {
        setEasterEggVisible(true);
      };

      document.addEventListener("click", handleClickOutside);

      return () => {
        document.removeEventListener("click", handleClickOutside);
      };
    }
  }, [isEasterEggVisible]);

  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout classname="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt="CosdeBucks"
                className="w-full h-auto lg:hidden md:inline-block md:w-full pt-0 md:pt-16 sm:pt-8"
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Convirtiendo visión en realidad con código y diseño."
                className="!text-4xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl my-4 font-medium "
              />
              <p className="my-4 text-base font-medium md:text-sm xs:text-sm">
                Soy un desarrollador web autodidacta con experiencia. Mi enfoque
                está en aprender de forma continua y aplicar esos conocimientos
                en proyectos de forma práctica para ello He trabajado en una
                variedad de proyectos para mejorar en mi rendimiento y
                habilidades técnicas.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/Cv2.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  Curriculum <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <a
                  href="mailto:p.avilaf1998@gmail.com"
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                >
                  Contacto
                </a>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div
          className="absolute right-8 bottom-8 inline-block w-16 md:hidden"
          onClick={handleLightBulbClick}
        >
          <Image
            src={lightBulb}
            alt="Codebucks"
            //Cobertura de animacion
            className="w-full h-auto animate-spin-slow pt-0 md:pt-16 sm:pt-8"
            style={{
              animationIterationCount: "1",
              animationTimingFunction: "cubic-bezier(0.68, -0.55, 0.265, 1.55)",
            }}
          />
        </div>
        {isEasterEggVisible && (
          <div className="fixed top-0 left-0 w-full h-full bg-black bg-opacity-75 flex items-center justify-center">
            <video
              src="/videos/easter-egg.mp4"
              className="max-w-full max-h-full"
              autoPlay
              controls
              onEnded={() => setEasterEggVisible(false)}
            />
          </div>
        )}
      </main>
    </>
  );
}
