import React, { useState } from "react";
import Head from "next/head";
import Layout from "./components/Layout";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "./components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "../lib/Icons";
import HireMe from "./components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";

export default function Home() {
  // Define el estado para manejar el estado de la luz y la animación
  const [animateLightBulb, setAnimateLightBulb] = useState(false);
  const [isLightOn, setIsLightOn] = useState(false);

  // Define la función handleLightBulbClick
  const handleLightBulbClick = () => {
    // Reproduce el sonido correspondiente
    const sound = new Audio("/audio/breaker-switch-45684.mp3");
    sound.volume = 0.6;
    sound.play();

    // Cambia el estado de la luz
    setIsLightOn(!isLightOn);
    setAnimateLightBulb(true);

    // Restablecer el estado de la animación después de un breve retraso
    setTimeout(() => setAnimateLightBulb(false), 1000); // Ajusta el tiempo según la duración de la animación
  };

  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex relative items-center text-dark w-full  dark:text-light">
        <Layout classname="pt-0 md:pt-16 sm:pt-8 ">
          {/* Animation buble */}

          <div className="blob"></div>

          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-auto md:w-full sm:w-full">
              <Image
                src={profilePic}
                alt="CosdeBucks"
                className="w-full h-auto pt-2 xl:pt-16 lg:pt-14 md:pt-12 sm:pt-10 xs:pt-8 xxs:pt-4"
                priority
                sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText
                text="Convirtiendo visión en realidad con código y diseño."
                className="!text-4xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl my-4 font-medium"
              />
              <p className="my-4 mr-2 text-base font-medium md:text-sm xs:text-sm">
                Soy un desarrollador web autodidacta con experiencia en la
                creacion de paginas webs FullStack. Mi enfoque está en aprender
                de forma continua y aplicar esos conocimientos en proyectos de
                forma práctica para ello He trabajado en variedad de proyectos
                personales y para clientes para mejorar en mi rendimiento y
                habilidades técnicas lo cual me ha permitodo entender las
                necesidades de los clientes y como llevar a cabo un proyecto de
                forma exitosa.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/Cv Profesional-Patricio.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  CV
                  <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <a
                  href="mailto:p.avilaf1998@gmail.com"
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base sm:top-4 md:top-8 relative"
                >
                  Contacto
                </a>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div
          className={`absolute right-8 bottom-8 inline-block w-16 md:hidden ${
            animateLightBulb ? "animate-lightbulb" : ""
          }`}
          onClick={handleLightBulbClick}
        >
          <Image
            src={lightBulb}
            alt="Codebucks"
            className="w-full h-auto left-0  cursor-pointer"
            style={{
              filter: isLightOn
                ? "drop-shadow(0 0 30px rgba(255, 255, 0, 1))"
                : "none", // Intensifica el filtro cuando la luz está encendida
            }}
          />
        </div>
      </main>
    </>
  );
}
