import Head from 'next/head'
import Layout from './components/Layout'
import Image from 'next/image'
import profilePic from '../../public/images/profile/developer-pic-1.png'
import AnimatedText from './components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '../lib/Icons'
import HireMe from './components/HireMe'
import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
      <main className=' flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout classname='pt-0'>
          <div className=' flex items-center justify-between w-full'>
            <div className=' w-1/2'>
              <Image src={profilePic} alt="CosdeBucks" className='w-full h-auto animate-pulse ' style={{ animationIterationCount: '1',
                 animationDuration: '3s' }} />  
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <h1>   </h1>
              <AnimatedText text= "Convirtiendo visión   en realidad  con código y diseño." 
                className='!text-4xl !text-left '
              />
              <p className='my-4 text-base font-medium'>
               Como desarrollador full-stack, me dedico a convertir ideas en aplicaciones web innovadoras. Explora mis últimos proyectos y artículos, donde podrás ver mi experiencia en desarrollo web.
              </p>
              <div className='flex items-center self-start mt-2'>
                <Link href= "/Cv.pdf" target={"_blank"}
                className="flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark

                dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                hover:dark:border-light
                "
                download={true}
                >Curriculum <LinkArrow className={"w-6 ml-1"}></LinkArrow>
                
                </Link>
                
                <a href="mailto:p.avilaf1998@gmail.com" 
                className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light"
                >Contacto</a>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe/>
        <div className='absolute right-8 bottom-8 inline-block w-24'>
          <Image src={lightBulb} alt='Codebucks' className='w-full h-auto animate-spin-slow' 
           style={{ animationIterationCount: '1',
           animationTimingFunction: 'cubic-bezier(0.68, -0.55, 0.265, 1.55)'
         }}/>
        </div>
      </main>
    </>
  )
}
